# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Login to GCR'
      inputs:
        command: login
        containerRegistry: gcrServiceConnection
    - task: Docker@2
      displayName: Build docker image
      inputs:
        containerRegistry: 'gcrServiceConnection'
        repository: 'prod-bip/ssb/dapla/blueprint'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: '$(Build.SourceBranchName)-imagescan-$(Build.SourceVersion)'