version: '3.7'

services:

  neo4j:
    image: neo4j:4.0
    ports:
      - 27474:7474
      - 27687:7687
    environment:
      NEO4J_AUTH: neo4j/secret

  blueprint:
    container_name: blueprint
    build:
      context: ../dapla-blueprint
      dockerfile: Dockerfile
    image: dapla-blueprint:dev
    ports:
      - 20170:10170
    depends_on:
      - neo4j