server:
  port: 10220
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"
#  experimental:
#    http2:
#      enable: true
#      max-content-length: 16384

neo4j:
  host: localhost
  port: 7687
  username: neo4j
  password: password

tracing:
  enabled: false
  service: test-application
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/live"
      enabled: false
    - path: "/health/ready"
      enabled: false

openapi:
